script:
- apt update
- apt install git autoconf libtool pkg-config python g++ libusb-dev # libusb-1.0-0-dev
- git clone https://github.com/networkupstools/nut.git
- cd nut
- # git checkout libusb-1.0
- ./autogen.sh
- ./configure --with-usb
- make

addons:
  artifacts:
    paths:
    - drivers/usbhid-ups
  
